name: Release

on:
  workflow_call:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20.2'

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: go install

      - name: Build Project
        run: make build

      - name: Generate Release
        id: relgen
        run: ./bin/relgen && cat version.txt | sed 's/ *$//g' | xargs -I '{}' echo 'version={}' >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        run: gh release create '${{ steps.relgen.outputs.version }}' --notes-file changelog-entry.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}